import { Permission, SystemRoleName } from "../generated/client";

/**
 * Default permission grants for each built-in system role.
 * Clinic Owners can still create custom roles per-tenant with a subset/superset
 * of these via the Role model; this map only seeds the defaults.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<SystemRoleName, Permission[]> = {
  SUPER_ADMIN: Object.values(Permission),
  CLINIC_OWNER: Object.values(Permission).filter(
    (p) => p !== Permission.SYSTEM_MANAGE_TENANTS && p !== Permission.DIRECTORY_MANAGE,
  ),
  MANAGER: [
    Permission.DASHBOARD_VIEW,
    Permission.PATIENTS_READ,
    Permission.PATIENTS_WRITE,
    Permission.APPOINTMENTS_READ,
    Permission.APPOINTMENTS_WRITE,
    Permission.APPOINTMENTS_DELETE,
    Permission.DOCTORS_READ,
    Permission.DOCTORS_WRITE,
    Permission.DEPARTMENTS_MANAGE,
    Permission.BILLING_READ,
    Permission.BILLING_WRITE,
    Permission.INSURANCE_MANAGE,
    Permission.INVENTORY_READ,
    Permission.INVENTORY_WRITE,
    Permission.REPORTS_VIEW,
    Permission.MESSAGES_READ,
    Permission.MESSAGES_WRITE,
    Permission.STAFF_MANAGE,
    Permission.AUDIT_LOG_VIEW,
    Permission.SETTINGS_MANAGE,
  ],
  RECEPTIONIST: [
    Permission.DASHBOARD_VIEW,
    Permission.PATIENTS_READ,
    Permission.PATIENTS_WRITE,
    Permission.APPOINTMENTS_READ,
    Permission.APPOINTMENTS_WRITE,
    Permission.DOCTORS_READ,
    Permission.BILLING_READ,
    Permission.BILLING_WRITE,
    Permission.MESSAGES_READ,
    Permission.MESSAGES_WRITE,
  ],
  DOCTOR: [
    Permission.DASHBOARD_VIEW,
    Permission.PATIENTS_READ,
    Permission.PATIENTS_WRITE,
    Permission.APPOINTMENTS_READ,
    Permission.APPOINTMENTS_WRITE,
    Permission.MEDICAL_RECORDS_READ,
    Permission.MEDICAL_RECORDS_WRITE,
    Permission.PRESCRIPTIONS_READ,
    Permission.PRESCRIPTIONS_WRITE,
    Permission.LAB_READ,
    Permission.LAB_WRITE,
    Permission.RADIOLOGY_READ,
    Permission.RADIOLOGY_WRITE,
    Permission.MESSAGES_READ,
    Permission.MESSAGES_WRITE,
  ],
  ASSISTANT: [
    Permission.DASHBOARD_VIEW,
    Permission.PATIENTS_READ,
    Permission.APPOINTMENTS_READ,
    Permission.MEDICAL_RECORDS_READ,
    Permission.LAB_READ,
    Permission.RADIOLOGY_READ,
    Permission.MESSAGES_READ,
  ],
  LABORATORY: [
    Permission.DASHBOARD_VIEW,
    Permission.PATIENTS_READ,
    Permission.LAB_READ,
    Permission.LAB_WRITE,
    Permission.MESSAGES_READ,
  ],
  RADIOLOGY: [
    Permission.DASHBOARD_VIEW,
    Permission.PATIENTS_READ,
    Permission.RADIOLOGY_READ,
    Permission.RADIOLOGY_WRITE,
    Permission.MESSAGES_READ,
  ],
  ACCOUNTANT: [
    Permission.DASHBOARD_VIEW,
    Permission.PATIENTS_READ,
    Permission.BILLING_READ,
    Permission.BILLING_WRITE,
    Permission.INSURANCE_MANAGE,
    Permission.REPORTS_VIEW,
    Permission.MESSAGES_READ,
  ],
};
